name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: ${{ !startsWith(github.event.pull_request.title, '[WIP]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
             sudo apt-get update
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get -y install --no-install-recommends libcunit1 libcunit1-dev
      
      - name: show gcc version
        run: gcc --version
      
      - name: show gcov version
        run: gcov --version

      - name: run unit test with coverage
        run: make unittest-with-coverage
      
      - name: run end-to-end test
        run: make e2etest
