name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
             sudo apt-get update
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get -y install --no-install-recommends libcunit1 libcunit1-dev

      - name: Show gcc version
        run: gcc --version

      - name: Show gcov version
        run: gcov --version

      - name: Run unit test
        run: make unittest

  unittest-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
             sudo apt-get update
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get -y install --no-install-recommends libcunit1 libcunit1-dev

      - name: Show gcc version
        run: gcc --version

      - name: Show gcov version
        run: gcov --version

      - name: Run unit test with coverage
        run: make unittest-cov

  e2etest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show gcc version
        run: gcc --version

      - name: Show gcov version
        run: gcov --version

      - name: Run end-to-end test
        run: make e2etest
