name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    if: ${{ !startsWith(github.event.pull_request.title, '[WIP]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
             sudo apt-get update
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get -y install --no-install-recommends libcunit1 libcunit1-dev
      - name: Show gcc version
        run: gcc --version
      - name: Show gcov version
        run: gcov --version

  unittest:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit test
        run: make unittest

  unittest-cov:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit test with coverage
        run: make unittest-cov

e2etest:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run end-to-end test
        run: make e2etest
